name: xcode

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project CelMek\ Viewer.xcodeproj -scheme 'CelMek Viewer'
